"use client";

import { useMemo, useState } from "react";
import HypothesisForm from "@/components/HypothesisForm";
import ElementCard from "@/components/ElementCard";
import { ValuationInput, Hypothesis, ReviewedElement } from "@/lib/types";
import {
  ReviewSectionModel,
  toReviewSections,
  toExportSections,
} from "@/lib/review";

export default function Home() {
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [source, setSource] = useState<"model" | "demo" | null>(null);
  const [modelName, setModelName] = useState<string>("");
  const [companyName, setCompanyName] = useState<string>("");
  const [summary, setSummary] = useState<string>("");
  const [sections, setSections] = useState<ReviewSectionModel[]>([]);
  const [exporting, setExporting] = useState(false);

  async function handleGenerate(input: ValuationInput) {
    setLoading(true);
    setError(null);
    setSource(null);
    try {
      const res = await fetch("/api/generate", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(input),
      });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Generation failed.");
      const hypothesis = data.hypothesis as Hypothesis;
      setCompanyName(input.companyName);
      setSummary(hypothesis.summary);
      setSections(toReviewSections(hypothesis));
      setSource(data.source);
      setModelName(data.model);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setLoading(false);
    }
  }

  function updateElement(sectionKey: string, next: ReviewedElement) {
    setSections((prev) =>
      prev.map((s) =>
        s.key !== sectionKey
          ? s
          : { ...s, elements: s.elements.map((el) => (el.id === next.id ? next : el)) },
      ),
    );
  }

  function bulkAccept() {
    setSections((prev) =>
      prev.map((s) => ({
        ...s,
        elements: s.elements.map((el) =>
          el.decision === "pending" ? { ...el, decision: "accepted" as const } : el,
        ),
      })),
    );
  }

  const stats = useMemo(() => {
    const all = sections.flatMap((s) => s.elements);
    return {
      total: all.length,
      accepted: all.filter((e) => e.decision === "accepted").length,
      amended: all.filter((e) => e.decision === "amended").length,
      rejected: all.filter((e) => e.decision === "rejected").length,
      pending: all.filter((e) => e.decision === "pending").length,
    };
  }, [sections]);

  async function handleExport() {
    setExporting(true);
    setError(null);
    try {
      const meta = `Reviewed ${stats.accepted + stats.amended} of ${stats.total} proposed elements · ${new Date().toLocaleString()}`;
      const res = await fetch("/api/export", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          companyName,
          meta,
          sections: [
            { title: "Summary", items: summary ? [summary] : [] },
            ...toExportSections(sections),
          ],
        }),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Export failed.");
      }
      const blob = await res.blob();
      const url = URL.createObjectURL(blob);
      const a = document.createElement("a");
      a.href = url;
      a.download = `${companyName || "valuation"}-hypothesis.docx`;
      a.click();
      URL.revokeObjectURL(url);
    } catch (e: any) {
      setError(e.message);
    } finally {
      setExporting(false);
    }
  }

  const hasResult = sections.length > 0;

  return (
    <div className="space-y-6">
      <HypothesisForm onSubmit={handleGenerate} loading={loading} />

      {error && (
        <div className="rounded-md border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-800">
          {error}
        </div>
      )}

      {source === "demo" && (
        <div className="rounded-md border border-amber-200 bg-amber-50 px-4 py-3 text-sm text-amber-800">
          <strong>Demo mode</strong> — no model API key configured, so a sample
          hypothesis is shown. Set <code>LLM_API_KEY</code> /{" "}
          <code>LLM_BASE_URL</code> / <code>LLM_MODEL</code> to use a real model.
        </div>
      )}

      {hasResult && (
        <section className="space-y-5">
          <div className="card">
            <div className="flex flex-wrap items-center justify-between gap-3">
              <div>
                <h2 className="text-lg font-semibold">
                  Valuation hypothesis — {companyName}
                </h2>
                {source === "model" && (
                  <p className="text-xs text-slate-500">Generated by model: {modelName}</p>
                )}
              </div>
              <div className="flex gap-2">
                <button className="btn-ghost" onClick={bulkAccept} type="button">
                  Accept all pending
                </button>
                <button
                  className="btn-primary"
                  onClick={handleExport}
                  type="button"
                  disabled={exporting}
                >
                  {exporting ? "Exporting…" : "Export to Word"}
                </button>
              </div>
            </div>
            <p className="mt-3 text-sm leading-relaxed text-slate-700">{summary}</p>
            <div className="mt-3 flex flex-wrap gap-2 text-xs">
              <span className="chip bg-slate-100 text-slate-600">
                {stats.total} elements
              </span>
              <span className="chip bg-emerald-100 text-emerald-800">
                {stats.accepted} accepted
              </span>
              <span className="chip bg-amber-100 text-amber-800">
                {stats.amended} amended
              </span>
              <span className="chip bg-rose-100 text-rose-800">
                {stats.rejected} rejected
              </span>
              <span className="chip bg-slate-100 text-slate-500">
                {stats.pending} pending
              </span>
            </div>
          </div>

          {sections.map((section) => (
            <div key={section.key} className="space-y-3">
              <h3 className="text-sm font-semibold uppercase tracking-wide text-slate-500">
                {section.title}
              </h3>
              <div className="grid grid-cols-1 gap-3">
                {section.elements.map((el) => (
                  <ElementCard
                    key={el.id}
                    element={el}
                    onChange={(next) => updateElement(section.key, next)}
                  />
                ))}
              </div>
            </div>
          ))}
        </section>
      )}
    </div>
  );
}
